CLASS zcl_cac_model DEFINITION
  PUBLIC
  INHERITING FROM zcl_cac_model_abs
  CREATE PRIVATE

  GLOBAL FRIENDS zcl_cac_model_common .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_cac_model IMPLEMENTATION.
ENDCLASS.
